#!/usr/bin/env bash

# There still is the issue of differing odml ids if the same files are converted
# multiple times from datacite to odml and imported as rdf.
# Ideally old files are kept and only new files are imported.
# Maybe there should be a private gin repo that contains all required scripts
# and already converted odml / rdf files -> probably feasible approach.

# script requires an installed gin client with a logged in user able to
# to download the gin:G-Node/DOIMetadata and gin:G-Node/meta-source repositories.

echo "... checking doi fork"
if ! gin repoinfo G-Node/DOIMetadata | grep -iq "[error]"; then
  echo "... could not access G-Node/DOIMetadata; check gin login"
  exit 1
fi

# paths and scripts
# TODO change when using gin repo as base for script and already available files
ROOT=/home/${USER}/Chaos/staging/tmp/meta_source
CRCNS_SCRIPT_LOCATION=/home/${USER}/Chaos/work/snippets/staging/sh/meta_source/
CRCNS_SCRIPT=crcns_scrape_datacite

# create main file structure
mkdir -vp ${ROOT}/import_tmp/crcns
mkdir -vp ${ROOT}/import_tmp/gnode
mkdir -vp ${ROOT}/datacite/crcns
mkdir -vp ${ROOT}/datacite/gnode
mkdir -vp ${ROOT}/odml/crcns
mkdir -vp ${ROOT}/odml/gnode
mkdir -vp ${ROOT}/rdf/crcns
mkdir -vp ${ROOT}/rdf/gnode

# collect script files
cp ${CRCNS_SCRIPT_LOCATION}${CRCNS_SCRIPT} ${ROOT}/

# fetch CRCNS datacite files
echo "... collecting CRCNS datacite files to ${ROOT}/import_tmp/crcns/datacite"
cd ${ROOT}/import_tmp/crcns
bash ${ROOT}/${CRCNS_SCRIPT}

echo "... collected CRCNS datacite files; there should be >= 130 files available"
ls ${ROOT}/import_tmp/crcns/datacite | wc

echo "... check README and ${ROOT}/import_tmp/crcns/crcns_doi_id_log for details on potentially missing Datacite files"

echo "... running new CRCNS files check"
diff ${ROOT}/datacite/crcns/ ${ROOT}/import_tmp/crcns/datacite/ | awk '{print $4}' > ${ROOT}/import_tmp/crcns_new_files

echo "... new CRCNS datacite files"
wc -l ${ROOT}/import_tmp/crcns_new_files

# fetch DOIMetadata repository
echo "... fetching G-Node datacite files to ${ROOT}/import_tmp/gnode/DOIMetadata"
cd ${ROOT}/import_tmp/gnode
gin get G-Node/DOIMetadata

echo "... running new G-Node files check"
diff ${ROOT}/datacite/gnode/ ${ROOT}/import_tmp/gnode/DOIMetadata | grep '.xml' | awk '{print $4}' > ${ROOT}/import_tmp/gnode_new_files

echo "... new G-Node datacite files"
wc -l ${ROOT}/import_tmp/gnode_new_files
