#!/usr/bin/env bash

# There still is the issue of differing odml ids if the same files are converted
# multiple times from datacite to odml and imported as rdf.
# Ideally old files are kept and only new files are imported.
# Maybe there should be a private gin repo that contains all required scripts
# and already converted odml / rdf files -> probably feasible approach.

# script requires an installed gin client with a logged in user able to
# to download the gin:G-Node/DOIMetadata and gin:G-Node/meta-source repositories.

echo "... checking doi fork"
if ! gin repoinfo G-Node/DOIMetadata | grep -iq "[error]"; then
  echo "... could not access G-Node/DOIMetadata; check gin login"
  exit 1
fi

# paths and scripts
ROOT=/home/$USER/Chaos/staging/meta_source
CRCNS_SCRIPT_LOCACTION=/home/$USER/Chaos/work/snippets/staging/sh/meta_source/
CRCNS_SCRIPT=crcns_scrape_datacite

# create main file structure
mkdir -vp $ROOT/datacite/crcns
mkdir -vp $ROOT/datacite/gnode
mkdir -vp $ROOT/odml/crcns
mkdir -vp $ROOT/odml/gnode
mkdir -vp $ROOT/rdf/crcns
mkdir -vp $ROOT/rdf/gnode

# collect all script files
cp $CRCNS_SCRIPT_LOCATION$CRCNS_SCRIPT $ROOT

# fetch CRCNS datacite files
cd $ROOT/datacite/crcns
bash $ROOT/$CRCNS_SCRIPT

# fetch DOIMetadata repository
cd $ROOT/datacite/gnode
gin get G-Node/DOIMetadata
