#!/usr/bin/env bash
# Home folder containing data base, config files and figures
GCAHOME=/web/gca

# Set up project data base folders
GCAPGRESDB=$GCAHOME/postgres/
GCAPGRESSCRIPTS=$GCAHOME/scripts/

# Play framework setup
GCACONF=$GCAHOME/conf/
GCAIMAGES=$GCAHOME/images
GCAFIG=$GCAIMAGES/figures/
GCAFIGMOBILE=$GCAIMAGES/figures_mobile/

GCAPGRESIMG=postgres:11
GCAIMG=mpsonntag/gca-web:latest

# Pull all required docker containers
sudo docker pull $GCAPGRESIMG
sudo docker pull $GCAIMG

# Initialize the postgres database
GCAPGRES=pgres_gca_bee

sudo docker run -dit --rm --name $GCAPGRES -v $GCAPGRESDB:/var/lib/postgresql/data -v $GCAPGRESSCRIPTS:/docker-entrypoint-initdb.d -p 5432:5432 $GCAPGRESIMG

sudo docker run -dit --rm --name $GCAPGRES -v $GCAPGRESDB:/var/lib/postgresql/data -v $GCAPGRESSCRIPTS:/docker-entrypoint-initdb.d -p 5432:5432 $GCAPGRESIMG

# Set up required database and roles; load the database; make sure to set the appropriate password.
sudo docker exec -it $GCAPGRES psql -Upostgres -dpostgres -c "CREATE ROLE play WITH LOGIN PASSWORD '';"
sudo docker exec -it $GCAPGRES psql -Upostgres -dpostgres -c "CREATE ROLE roplay WITH LOGIN PASSWORD '';"
sudo docker exec -it $GCAPGRES psql -Upostgres -dpostgres -c "CREATE DATABASE play OWNER play;"
sudo docker exec -it $GCAPGRES psql -Uplay -dplay -a -f /docker-entrypoint-initdb.d/backup.sql
sudo docker stop $GCAPGRES

# Set up the common docker container bridge
GCANET=gcanet
sudo docker network create $GCANET

# Start postgres database container
sudo docker run -dit --restart always --name $GCAPGRES --network=$GCANET -v $GCAPGRESDB:/var/lib/postgresql/data -p 5432:5432 $GCAPGRESIMG

# Start play framework container
GCA=gca_bee
sudo docker run -dit --restart always --name $GCA --network=$GCANET -v $GCACONF:/srv/gca/conf/ -v $GCAFIG:/srv/gca/figures/ -v $GCAFIGMOBILE:/srv/gca/figures_mobile/ -p 9000:9000 $GCAIMG

