#!/usr/bin/env bash
# Home folder containing data base, config files and figures
GCAHOME=/web/gca

# Set up project data base folders
GCAPGRESDB=$GCAHOME/postgres/
GCAPGRESSCRIPTS=$GCAHOME/scripts/

# Play framework setup
GCACONF=$GCAHOME/conf/
GCAIMAGES=$GCAHOME/images
GCAFIG=$GCAIMAGES/figures/
GCAFIGMOBILE=$GCAIMAGES/figures_mobile/
GCABANNER=$GCAIMAGES/banners/

# Create all required directories
sudo mkdir -p $GCAHOME

sudo mkdir -p $GCAPGRESDB
sudo mkdir -p $GCAPGRESSCRIPTS

sudo mkdir -p $GCACONF
sudo mkdir -p $GCAFIG
sudo mkdir -p $GCAFIGMOBILE
sudo mkdir -p $GCABANNER
sudo mkdir -p $GCAHOME/backup

# Create dedicated "gca" user and add it to the "docker"
# group; create all required directories with this user.
sudo useradd -M -G docker gca
sudo chown -R gca:gca $GCAHOME
# Disable login for user gca
sudo usermod -L gca
